{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "bitbucketRunnerAutoscaler.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "bitbucketRunnerAutoscaler.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "bitbucketRunnerAutoscaler.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
