{{- if .Values.controller.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bitbucketRunnerAutoscaler.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bitbucketRunnerAutoscaler.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bitbucketRunnerAutoscalerController.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bitbucketRunnerAutoscalerController.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "bitbucketRunnerAutoscaler.serviceAccountName" . }}
      tolerations: {{ include "bitbucketRunnerAutoscaler.controllerTolerations" . | nindent 8 }}
      nodeSelector: {{ include "bitbucketRunnerAutoscaler.controllerNodeSelector" . | nindent 8 }}
      containers:
      - name: controller
        image: {{ .Values.controller.image }}:{{ .Values.controller.tag }}
        volumeMounts:
        - name: config
          mountPath: /opt/conf/config
          readOnly: true
        - name: template
          mountPath: /opt/conf/job_template
          readOnly: true
        env:
        - name: BITBUCKET_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "bitbucketRunnerAutoscaler.secretName" . }}
              key: bitbucketUsername
        - name: BITBUCKET_APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "bitbucketRunnerAutoscaler.secretName" . }}
              key: bitbucketAppPassword
        imagePullPolicy: {{ .Values.controller.imagePullPolicy }}
      volumes:
        - name: config
          configMap:
            name: {{ template "bitbucketRunnerAutoscaler.fullname" . }}-config
            defaultMode: 0644
            items:
              - key: runners_config.yaml
                path: runners_config.yaml
        - name: {{ template "bitbucketRunnerAutoscaler.fullname" . }}-template
          configMap:
            name: template
            defaultMode: 0644
            items:
              - key: job.yaml.template
                path: job.yaml.template
{{- end }}
