{{- if .Values.runner.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bitbucketRunnerAutoscaler.runnerServiceAccountName" . }}
  namespace: bitbucket-runner
  {{- with .Values.runner.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "bitbucketRunnerAutoscaler.labels" . | nindent 4 }}
{{- end }}
