{{- include "bitbucketRunnerAutoscaler.runnerNamespaces" . }}
{{- range $namespace := .RunnerNamespaces }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bitbucketRunnerAutoscaler.fullname" $ }}-runner
  namespace: {{ $namespace }}
  labels:
    {{- include "bitbucketRunnerAutoscaler.labels" $ | nindent 4 }}
{{- end }}
