apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitbucketRunnerAutoscaler.fullname" . }}-template
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bitbucketRunnerAutoscaler.labels" . | nindent 4 }}
data:
  job.yaml.template: |
    apiVersion: v1
    kind: List
    items:
      - {{ include "bitbucketRunnerAutoscaler.templateSecret" . | nindent 8 }}
      - {{ include "bitbucketRunnerAutoscaler.templateJob" . | nindent 8 }}
