{{- $allNamespaces := (list) }}
{{- range .Values.runnerConfig.groups }}
  {{- $allNamespaces = append $allNamespaces .namespace }}
{{- end }}
{{- range $namespace := $allNamespaces | uniq }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace }}
{{- end }}
