apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitbucketRunnerAutoscaler.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bitbucketRunnerAutoscaler.labels" . | nindent 4 }}
data:
  runners_config.yaml: |
{{ .Values.runner.config | toYaml | indent 4 }}
