{{- if not .Values.credentialsSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: bitbucket-credentials
  namespace: {{ .Values.namespace }}
data:
  bitbucketUsername: {{ .Values.bitbucketUsername | b64enc | quote }}
  bitbucketAppPassword: {{ .Values.bitbucketAppPassword | b64enc | quote }}
{{- end }}
