{{- if not .Values.credentialsSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bitbucketRunnerAutoscaler.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bitbucketRunnerAutoscaler.labels" . | nindent 4 }}
data:
  bitbucketUsername: {{ .Values.credentialSecret.bitbucketUsername | b64enc | quote }}
  bitbucketAppPassword: {{ .Values.credentialSecret.bitbucketAppPassword | b64enc | quote }}
{{- end }}
