apiVersion: v2
name: bitbucket-runner-autoscaler
description: chart-description

type: application

version: 0.1.0

maintainers:
  - name: Labyrinth Labs
    email: contact@lablabs.io
    url: https://lablabs.io
